### ISSUE TITLE
TODOS: Todo List to Project

### ISSUE THREAD

**Issue by mjesusdev** [mjesusoj/PokemonGame#1]
- [x] Create Footer & add Github project and more

**Comment by mjesusdev** [comment]
Some changes:

- [x] Change Font to Chubbo: https://www.fontshare.com/fonts/chubbo
- [ ] Download files of Bootstrap
- [ ] Some changes on README ❗❗
